# Generated by Django 5.1 on 2024-08-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_delete_userchat'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='chats',
            field=models.ManyToManyField(related_name='user_chats', to='chat.chats'),
        ),
    ]
