# Generated by Django 5.1 on 2024-09-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0002_alter_groups_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groups",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
