# Generated by Django 5.1 on 2024-08-29 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_delete_userchat'),
        ('group', '0002_groups_users_delete_usersgrous'),
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.chats'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='group.groups'),
        ),
    ]
